INSERT INTO books (title, author, pub_year, genre) VALUES
('The Great Gatsby', 'F. Scott Fitzgerald', 1925, 'Classic'),
('1984', 'George Orwell', 1949, 'Dystopian'),
('To Kill a Mockingbird', 'Harper Lee', 1960, 'Fiction'),
('The Catcher in the Rye', 'J.D. Salinger', 1951, 'Classic'),
('The Hobbit', 'J.R.R. Tolkien', 1937, 'Fantasy'),
('Fahrenheit 451', 'Ray Bradbury', 1953, 'Dystopian'),
('Pride and Prejudice', 'Jane Austen', 1813, 'Romance'),
('Brave New World', 'Aldous Huxley', 1932, 'Dystopian'),
('The Catch-22', 'Joseph Heller', 1961, 'Satire'),
('The Grapes of Wrath', 'John Steinbeck', 1939, 'Fiction'),
('Moby Dick', 'Herman Melville', 1851, 'Adventure'),
('The Odyssey', 'Homer', -800, 'Epic'),
('Ulysses', 'James Joyce', 1922, 'Modernist'),
('War and Peace', 'Leo Tolstoy', 1869, 'Historical'),
('The Divine Comedy', 'Dante Alighieri', 1320, 'Epic'),
('The Brothers Karamazov', 'Fyodor Dostoevsky', 1880, 'Philosophical'),
('Crime and Punishment', 'Fyodor Dostoevsky', 1866, 'Psychological'),
('Madame Bovary', 'Gustave Flaubert', 1856, 'Realism'),
('The Iliad', 'Homer', -750, 'Epic'),
('One Hundred Years of Solitude', 'Gabriel García Márquez', 1967, 'Magic Realism');